const SUPPLIER_BY_CATEGORY = {
  abarrotes: "Central de abarrotes",
  bebidas: "Distribuidora de bebidas",
  botanas: "Botanas y snacks",
  dulces: "Dulces y golosinas",
  lacteos: "Lacteos regionales",
  higiene: "Higiene y cuidado personal",
  limpieza: "Limpieza y hogar",
  hogar: "Hogar y desechables",
  general: "Proveedor general",
};

const BRAND_BY_CATEGORY = {
  abarrotes: "Linea base",
  bebidas: "Linea refresco",
  botanas: "Linea snack",
  dulces: "Linea dulce",
  lacteos: "Linea lactea",
  higiene: "Linea cuidado",
  limpieza: "Linea limpieza",
  hogar: "Linea hogar",
  general: "Linea general",
};

function buildItem(name, category, price, cost, options = {}) {
  return {
    name,
    category,
    unit: options.unit || "pza",
    price,
    cost,
    stock: 0,
    minStock: options.minStock ?? (options.unit === "paq" || options.unit === "caja" ? 4 : 6),
    sku: options.sku || null,
    barcode: options.barcode || null,
    brand: options.brand || BRAND_BY_CATEGORY[category] || "Linea base",
    supplierName: options.supplierName || SUPPLIER_BY_CATEGORY[category] || "Proveedor general",
    packSize: options.packSize ?? null,
    typeCode: options.typeCode || null,
  };
}

const starterCatalog = [
  buildItem("Arroz Verde Valle 900 g", "abarrotes", 29.5, 22.0, { sku: "ABA-001", brand: "Verde Valle" }),
  buildItem("Frijol Isadora pinto 900 g", "abarrotes", 34.0, 26.0, { sku: "ABA-002", brand: "Isadora" }),
  buildItem("Azucar Zulka estandar 1 kg", "abarrotes", 31.0, 24.5, { sku: "ABA-003", brand: "Zulka" }),
  buildItem("Sal La Fina de mesa 1 kg", "abarrotes", 18.0, 12.5, { sku: "ABA-004", brand: "La Fina" }),
  buildItem("Harina de maiz Maseca 1 kg", "abarrotes", 27.0, 20.0, { sku: "ABA-005", brand: "Maseca" }),
  buildItem("Harina Selecta de trigo 1 kg", "abarrotes", 25.0, 18.5, { sku: "ABA-006", brand: "Selecta" }),
  buildItem("Aceite Capullo vegetal 850 ml", "abarrotes", 43.0, 35.0, { sku: "ABA-007", brand: "Capullo" }),
  buildItem("Atun Dolores en agua 140 g", "abarrotes", 24.0, 18.0, { sku: "ABA-008", brand: "Dolores" }),
  buildItem("Mayonesa McCormick 390 g", "abarrotes", 36.0, 28.0, { sku: "ABA-009", brand: "McCormick" }),
  buildItem("Catsup Del Monte 397 g", "abarrotes", 29.0, 22.0, { sku: "ABA-010", brand: "Del Monte" }),
  buildItem("Salsa Valentina 370 ml", "abarrotes", 24.0, 17.5, { sku: "ABA-011", brand: "Valentina" }),
  buildItem("Pure Del Fuerte 210 g", "abarrotes", 11.5, 8.0, { sku: "ABA-012", minStock: 10, brand: "Del Fuerte" }),
  buildItem("Pasta La Moderna spaghetti 200 g", "abarrotes", 14.5, 10.5, { sku: "ABA-013", minStock: 8, brand: "La Moderna" }),
  buildItem("Sopa La Moderna codito 200 g", "abarrotes", 13.5, 9.5, { sku: "ABA-014", minStock: 8, brand: "La Moderna" }),
  buildItem("Avena Quaker 400 g", "abarrotes", 23.0, 17.0, { sku: "ABA-015", brand: "Quaker" }),
  buildItem("Cafe soluble Nescafe 100 g", "abarrotes", 69.0, 55.0, { sku: "ABA-016", minStock: 3, brand: "Nescafe" }),
  buildItem("Cereal Kellogg's hojuelas 500 g", "abarrotes", 48.0, 37.0, { sku: "ABA-017", brand: "Kellogg's" }),
  buildItem("Galleta Gamesa Maria 170 g", "abarrotes", 19.5, 14.0, { sku: "ABA-018", brand: "Gamesa" }),
  buildItem("Tostadas Charras horneadas 300 g", "abarrotes", 32.0, 24.0, { sku: "ABA-019", brand: "Charras" }),
  buildItem("Mermelada McCormick fresa 270 g", "abarrotes", 32.0, 24.0, { sku: "ABA-020", brand: "McCormick" }),
  buildItem("Pan Bimbo blanco grande", "abarrotes", 49.0, 39.0, { sku: "ABA-021", brand: "Bimbo", minStock: 4 }),
  buildItem("Tortillinas Tia Rosa 22 pzas", "abarrotes", 34.0, 26.0, { sku: "ABA-022", brand: "Tia Rosa", minStock: 4 }),

  buildItem("Ciel agua purificada 600 ml", "bebidas", 12.0, 8.5, { sku: "BEB-001", minStock: 12, brand: "Ciel" }),
  buildItem("Bonafont agua purificada 1.5 L", "bebidas", 18.0, 12.5, { sku: "BEB-002", minStock: 8, brand: "Bonafont" }),
  buildItem("Coca-Cola 600 ml", "bebidas", 19.0, 14.0, { sku: "BEB-003", minStock: 12, brand: "Coca-Cola" }),
  buildItem("Coca-Cola 2.5 L", "bebidas", 42.0, 33.0, { sku: "BEB-004", minStock: 6, brand: "Coca-Cola" }),
  buildItem("Fanta naranja 600 ml", "bebidas", 19.0, 14.0, { sku: "BEB-005", minStock: 10, brand: "Fanta" }),
  buildItem("Sprite 600 ml", "bebidas", 19.0, 14.0, { sku: "BEB-006", minStock: 10, brand: "Sprite" }),
  buildItem("Fuze Tea te helado 600 ml", "bebidas", 20.0, 15.0, { sku: "BEB-007", minStock: 8, brand: "Fuze Tea" }),
  buildItem("Powerade bebida isotonic 625 ml", "bebidas", 24.0, 18.5, { sku: "BEB-008", minStock: 8, brand: "Powerade" }),
  buildItem("Monster bebida energetica 473 ml", "bebidas", 39.0, 30.0, { sku: "BEB-009", minStock: 4, brand: "Monster" }),
  buildItem("Jumex mango 1 L", "bebidas", 31.0, 24.0, { sku: "BEB-010", minStock: 6, brand: "Jumex" }),
  buildItem("Del Valle naranja 500 ml", "bebidas", 20.0, 15.0, { sku: "BEB-011", minStock: 8, brand: "Del Valle" }),
  buildItem("Santa Clara horchata 1 L", "bebidas", 27.0, 20.0, { sku: "BEB-012", minStock: 5, brand: "Santa Clara" }),
  buildItem("Nescafe listo en lata 240 ml", "bebidas", 26.0, 19.5, { sku: "BEB-013", minStock: 6, brand: "Nescafe" }),
  buildItem("Topo Chico agua mineral 355 ml", "bebidas", 17.0, 12.5, { sku: "BEB-014", minStock: 8, brand: "Topo Chico" }),

  buildItem("Sabritas original 45 g", "botanas", 18.0, 12.5, { sku: "BOT-001", minStock: 10, brand: "Sabritas" }),
  buildItem("Sabritas adobadas 45 g", "botanas", 18.0, 12.5, { sku: "BOT-002", minStock: 10, brand: "Sabritas" }),
  buildItem("Nipon cacahuate japones 100 g", "botanas", 20.0, 14.0, { sku: "BOT-003", minStock: 8, brand: "Nipon" }),
  buildItem("Act II palomitas microondas 90 g", "botanas", 26.0, 19.0, { sku: "BOT-004", minStock: 6, brand: "Act II" }),
  buildItem("Barcel churritos picantes 65 g", "botanas", 16.0, 11.0, { sku: "BOT-005", minStock: 8, brand: "Barcel" }),
  buildItem("Totis totopos 300 g", "botanas", 32.0, 24.0, { sku: "BOT-006", minStock: 6, brand: "Totis" }),
  buildItem("Gamesa Emperador chocolate", "botanas", 19.0, 13.5, { sku: "BOT-007", minStock: 8, brand: "Gamesa" }),
  buildItem("Gamesa Saladitas 180 g", "botanas", 23.0, 17.0, { sku: "BOT-008", minStock: 8, brand: "Gamesa" }),
  buildItem("Kacang semillas mixtas 90 g", "botanas", 24.0, 17.5, { sku: "BOT-009", minStock: 6, brand: "Kacang" }),

  buildItem("Carlos V chocolate barra 20 g", "dulces", 14.0, 9.5, { sku: "DUL-001", minStock: 12, brand: "Carlos V" }),
  buildItem("Panditas gomitas bolsa 100 g", "dulces", 21.0, 15.0, { sku: "DUL-002", minStock: 8, brand: "Panditas" }),
  buildItem("Werther's Original surtido 150 g", "dulces", 24.0, 17.0, { sku: "DUL-003", minStock: 8, brand: "Werther's" }),
  buildItem("Vero paleta enchilada 1 pza", "dulces", 8.0, 4.5, { sku: "DUL-004", minStock: 20, brand: "Vero" }),
  buildItem("Clorets menta 1 pza", "dulces", 7.0, 4.0, { sku: "DUL-005", minStock: 20, brand: "Clorets" }),
  buildItem("De la Rosa mazapan 1 pza", "dulces", 9.0, 5.0, { sku: "DUL-006", minStock: 15, brand: "De la Rosa" }),
  buildItem("La Costena malvavisco bolsa 120 g", "dulces", 20.0, 14.5, { sku: "DUL-007", minStock: 6, brand: "La Costena" }),
  buildItem("Gamesa Arcoiris vainilla", "dulces", 17.0, 12.5, { sku: "DUL-008", minStock: 8, brand: "Gamesa" }),
  buildItem("Gansito Marinela 1 pza", "dulces", 19.0, 13.0, { sku: "DUL-009", minStock: 10, brand: "Marinela" }),

  buildItem("Lala leche entera 1 L", "lacteos", 31.0, 24.5, { sku: "LAC-001", minStock: 8, brand: "Lala" }),
  buildItem("Lala leche deslactosada 1 L", "lacteos", 34.0, 27.0, { sku: "LAC-002", minStock: 6, brand: "Lala" }),
  buildItem("Yoplait yogur bebible fresa 220 ml", "lacteos", 18.0, 13.0, { sku: "LAC-003", minStock: 8, brand: "Yoplait" }),
  buildItem("Lala yogur natural 900 g", "lacteos", 42.0, 33.0, { sku: "LAC-004", minStock: 4, brand: "Lala" }),
  buildItem("Nochebuena queso panela 400 g", "lacteos", 58.0, 46.0, { sku: "LAC-005", minStock: 4, brand: "Nochebuena" }),
  buildItem("Esmeralda queso oaxaca 400 g", "lacteos", 63.0, 50.0, { sku: "LAC-006", minStock: 4, brand: "Esmeralda" }),
  buildItem("Lala crema acida 425 g", "lacteos", 29.0, 22.0, { sku: "LAC-007", minStock: 5, brand: "Lala" }),
  buildItem("Lurpak mantequilla 90 g", "lacteos", 20.0, 15.0, { sku: "LAC-008", minStock: 6, brand: "Lurpak" }),
  buildItem("San Juan huevo blanco 18 pzas", "lacteos", 52.0, 43.0, { sku: "LAC-009", unit: "paq", minStock: 4, brand: "San Juan" }),
  buildItem("Carnation leche evaporada 360 g", "lacteos", 25.0, 18.5, { sku: "LAC-010", minStock: 6, brand: "Carnation" }),

  buildItem("Palmolive jabon corporal 150 g", "higiene", 19.0, 13.5, { sku: "HIG-001", minStock: 8, brand: "Palmolive" }),
  buildItem("Head & Shoulders shampoo 750 ml", "higiene", 62.0, 49.0, { sku: "HIG-002", minStock: 4, brand: "Head & Shoulders" }),
  buildItem("Colgate pasta dental 100 ml", "higiene", 34.0, 26.0, { sku: "HIG-003", minStock: 5, brand: "Colgate" }),
  buildItem("Oral-B cepillo dental adulto", "higiene", 18.0, 12.5, { sku: "HIG-004", minStock: 6, brand: "Oral-B" }),
  buildItem("Axe desodorante aerosol 150 ml", "higiene", 57.0, 44.0, { sku: "HIG-005", minStock: 4, brand: "Axe" }),
  buildItem("Saba toalla femenina 10 pzas", "higiene", 34.0, 26.0, { sku: "HIG-006", unit: "paq", minStock: 5, brand: "Saba" }),
  buildItem("Kleenex papel facial caja 90 hojas", "higiene", 22.0, 16.5, { sku: "HIG-007", minStock: 6, brand: "Kleenex" }),
  buildItem("Huggies panuelos humedos 100 pzas", "higiene", 28.0, 21.0, { sku: "HIG-008", minStock: 5, brand: "Huggies" }),

  buildItem("Ariel detergente en polvo 1 kg", "limpieza", 43.0, 34.0, { sku: "LIM-001", minStock: 5, brand: "Ariel" }),
  buildItem("Ace detergente liquido 950 ml", "limpieza", 49.0, 38.5, { sku: "LIM-002", minStock: 4, brand: "Ace" }),
  buildItem("Zote jabon lavanderia 400 g", "limpieza", 18.0, 12.5, { sku: "LIM-003", minStock: 8, brand: "Zote" }),
  buildItem("Suavitel 850 ml", "limpieza", 34.0, 26.0, { sku: "LIM-004", minStock: 5, brand: "Suavitel" }),
  buildItem("Cloralex 950 ml", "limpieza", 17.0, 11.5, { sku: "LIM-005", minStock: 8, brand: "Cloralex" }),
  buildItem("Axion lavatrastes 750 ml", "limpieza", 31.0, 23.5, { sku: "LIM-006", minStock: 6, brand: "Axion" }),
  buildItem("Scotch-Brite esponja doble uso", "limpieza", 13.0, 8.5, { sku: "LIM-007", minStock: 8, brand: "Scotch-Brite" }),
  buildItem("Rino bolsa para basura 20 pzas", "limpieza", 34.0, 26.0, { sku: "LIM-008", unit: "paq", minStock: 4, brand: "Rino" }),

  buildItem("Pétalo papel higienico 4 rollos", "hogar", 29.0, 22.0, { sku: "HOG-001", unit: "paq", minStock: 6, brand: "Petalo" }),
  buildItem("Regio papel higienico 12 rollos", "hogar", 74.0, 60.0, { sku: "HOG-002", unit: "paq", minStock: 3, brand: "Regio" }),
  buildItem("Pétalo servilletas 500 pzas", "hogar", 28.0, 21.0, { sku: "HOG-003", unit: "paq", minStock: 5, brand: "Petalo" }),
  buildItem("Bounty toalla de cocina 2 rollos", "hogar", 36.0, 28.0, { sku: "HOG-004", unit: "paq", minStock: 4, brand: "Bounty" }),
  buildItem("Desechables Reyma vasos 25 pzas", "hogar", 23.0, 17.0, { sku: "HOG-005", unit: "paq", minStock: 5, brand: "Reyma" }),
  buildItem("Desechables Reyma platos 20 pzas", "hogar", 25.0, 18.5, { sku: "HOG-006", unit: "paq", minStock: 5, brand: "Reyma" }),
  buildItem("Duracell pilas AA 4 pzas", "hogar", 49.0, 38.0, { sku: "HOG-007", unit: "paq", minStock: 4, brand: "Duracell" }),
  buildItem("Bic encendedor utilitario", "hogar", 16.0, 10.5, { sku: "HOG-008", minStock: 8, brand: "Bic" }),
  buildItem("Philips foco led 9W", "hogar", 39.0, 29.5, { sku: "HOG-009", minStock: 4, brand: "Philips" }),
];

module.exports = {
  starterCatalog,
};
